/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyCodeRouteImport } from './routes/verify.$code'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardWorkspaceRouteImport } from './routes/_authenticated/dashboard.workspace'
import { Route as AuthenticatedDashboardTeachingRouteImport } from './routes/_authenticated/dashboard.teaching'
import { Route as AuthenticatedDashboardStartupRouteImport } from './routes/_authenticated/dashboard.startup'
import { Route as AuthenticatedDashboardSmeRouteImport } from './routes/_authenticated/dashboard.sme'
import { Route as AuthenticatedDashboardSchemaRouteImport } from './routes/_authenticated/dashboard.schema'
import { Route as AuthenticatedDashboardScfRouteImport } from './routes/_authenticated/dashboard.scf'
import { Route as AuthenticatedDashboardRiskRouteImport } from './routes/_authenticated/dashboard.risk'
import { Route as AuthenticatedDashboardReportsRouteImport } from './routes/_authenticated/dashboard.reports'
import { Route as AuthenticatedDashboardQuizzesRouteImport } from './routes/_authenticated/dashboard.quizzes'
import { Route as AuthenticatedDashboardProgressRouteImport } from './routes/_authenticated/dashboard.progress'
import { Route as AuthenticatedDashboardPayrollRouteImport } from './routes/_authenticated/dashboard.payroll'
import { Route as AuthenticatedDashboardNotificationsRouteImport } from './routes/_authenticated/dashboard.notifications'
import { Route as AuthenticatedDashboardMyListingsRouteImport } from './routes/_authenticated/dashboard.my-listings'
import { Route as AuthenticatedDashboardMessagesRouteImport } from './routes/_authenticated/dashboard.messages'
import { Route as AuthenticatedDashboardLegalLibraryRouteImport } from './routes/_authenticated/dashboard.legal-library'
import { Route as AuthenticatedDashboardLearningRouteImport } from './routes/_authenticated/dashboard.learning'
import { Route as AuthenticatedDashboardKpiRouteImport } from './routes/_authenticated/dashboard.kpi'
import { Route as AuthenticatedDashboardInvoicesRouteImport } from './routes/_authenticated/dashboard.invoices'
import { Route as AuthenticatedDashboardInvestmentRouteImport } from './routes/_authenticated/dashboard.investment'
import { Route as AuthenticatedDashboardHealthRouteImport } from './routes/_authenticated/dashboard.health'
import { Route as AuthenticatedDashboardG50RouteImport } from './routes/_authenticated/dashboard.g50'
import { Route as AuthenticatedDashboardEvaluationRouteImport } from './routes/_authenticated/dashboard.evaluation'
import { Route as AuthenticatedDashboardEnrollmentsRouteImport } from './routes/_authenticated/dashboard.enrollments'
import { Route as AuthenticatedDashboardDiscoveryRouteImport } from './routes/_authenticated/dashboard.discovery'
import { Route as AuthenticatedDashboardCoursesRouteImport } from './routes/_authenticated/dashboard.courses'
import { Route as AuthenticatedDashboardComplianceRouteImport } from './routes/_authenticated/dashboard.compliance'
import { Route as AuthenticatedDashboardCompanyRouteImport } from './routes/_authenticated/dashboard.company'
import { Route as AuthenticatedDashboardClientsRouteImport } from './routes/_authenticated/dashboard.clients'
import { Route as AuthenticatedDashboardCertificatesRouteImport } from './routes/_authenticated/dashboard.certificates'
import { Route as AuthenticatedDashboardCdeRouteImport } from './routes/_authenticated/dashboard.cde'
import { Route as AuthenticatedDashboardAuditRouteImport } from './routes/_authenticated/dashboard.audit'
import { Route as AuthenticatedDashboardAppointmentsRouteImport } from './routes/_authenticated/dashboard.appointments'
import { Route as AuthenticatedDashboardAnnualTaxRouteImport } from './routes/_authenticated/dashboard.annual-tax'
import { Route as AuthenticatedDashboardAnalysisRouteImport } from './routes/_authenticated/dashboard.analysis'
import { Route as AuthenticatedDashboardAiChatRouteImport } from './routes/_authenticated/dashboard.ai-chat'
import { Route as AuthenticatedDashboardAiChatIndexRouteImport } from './routes/_authenticated/dashboard.ai-chat.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as AuthenticatedDashboardStartupServiceRouteImport } from './routes/_authenticated/dashboard.startup.$service'
import { Route as AuthenticatedDashboardSmeServiceRouteImport } from './routes/_authenticated/dashboard.sme.$service'
import { Route as AuthenticatedDashboardCoursesSlugRouteImport } from './routes/_authenticated/dashboard.courses.$slug'
import { Route as AuthenticatedDashboardCdeModuleRouteImport } from './routes/_authenticated/dashboard.cde.$module'
import { Route as AuthenticatedDashboardAiChatThreadIdRouteImport } from './routes/_authenticated/dashboard.ai-chat.$threadId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardWorkspaceRoute =
  AuthenticatedDashboardWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTeachingRoute =
  AuthenticatedDashboardTeachingRouteImport.update({
    id: '/teaching',
    path: '/teaching',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardStartupRoute =
  AuthenticatedDashboardStartupRouteImport.update({
    id: '/startup',
    path: '/startup',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSmeRoute =
  AuthenticatedDashboardSmeRouteImport.update({
    id: '/sme',
    path: '/sme',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSchemaRoute =
  AuthenticatedDashboardSchemaRouteImport.update({
    id: '/schema',
    path: '/schema',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardScfRoute =
  AuthenticatedDashboardScfRouteImport.update({
    id: '/scf',
    path: '/scf',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardRiskRoute =
  AuthenticatedDashboardRiskRouteImport.update({
    id: '/risk',
    path: '/risk',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardReportsRoute =
  AuthenticatedDashboardReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardQuizzesRoute =
  AuthenticatedDashboardQuizzesRouteImport.update({
    id: '/quizzes',
    path: '/quizzes',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProgressRoute =
  AuthenticatedDashboardProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPayrollRoute =
  AuthenticatedDashboardPayrollRouteImport.update({
    id: '/payroll',
    path: '/payroll',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardNotificationsRoute =
  AuthenticatedDashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMyListingsRoute =
  AuthenticatedDashboardMyListingsRouteImport.update({
    id: '/my-listings',
    path: '/my-listings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMessagesRoute =
  AuthenticatedDashboardMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLegalLibraryRoute =
  AuthenticatedDashboardLegalLibraryRouteImport.update({
    id: '/legal-library',
    path: '/legal-library',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLearningRoute =
  AuthenticatedDashboardLearningRouteImport.update({
    id: '/learning',
    path: '/learning',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardKpiRoute =
  AuthenticatedDashboardKpiRouteImport.update({
    id: '/kpi',
    path: '/kpi',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardInvoicesRoute =
  AuthenticatedDashboardInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardInvestmentRoute =
  AuthenticatedDashboardInvestmentRouteImport.update({
    id: '/investment',
    path: '/investment',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardHealthRoute =
  AuthenticatedDashboardHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardG50Route =
  AuthenticatedDashboardG50RouteImport.update({
    id: '/g50',
    path: '/g50',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardEvaluationRoute =
  AuthenticatedDashboardEvaluationRouteImport.update({
    id: '/evaluation',
    path: '/evaluation',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardEnrollmentsRoute =
  AuthenticatedDashboardEnrollmentsRouteImport.update({
    id: '/enrollments',
    path: '/enrollments',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDiscoveryRoute =
  AuthenticatedDashboardDiscoveryRouteImport.update({
    id: '/discovery',
    path: '/discovery',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCoursesRoute =
  AuthenticatedDashboardCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardComplianceRoute =
  AuthenticatedDashboardComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCompanyRoute =
  AuthenticatedDashboardCompanyRouteImport.update({
    id: '/company',
    path: '/company',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardClientsRoute =
  AuthenticatedDashboardClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCertificatesRoute =
  AuthenticatedDashboardCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCdeRoute =
  AuthenticatedDashboardCdeRouteImport.update({
    id: '/cde',
    path: '/cde',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAuditRoute =
  AuthenticatedDashboardAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAppointmentsRoute =
  AuthenticatedDashboardAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAnnualTaxRoute =
  AuthenticatedDashboardAnnualTaxRouteImport.update({
    id: '/annual-tax',
    path: '/annual-tax',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAnalysisRoute =
  AuthenticatedDashboardAnalysisRouteImport.update({
    id: '/analysis',
    path: '/analysis',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAiChatRoute =
  AuthenticatedDashboardAiChatRouteImport.update({
    id: '/ai-chat',
    path: '/ai-chat',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAiChatIndexRoute =
  AuthenticatedDashboardAiChatIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardAiChatRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardStartupServiceRoute =
  AuthenticatedDashboardStartupServiceRouteImport.update({
    id: '/$service',
    path: '/$service',
    getParentRoute: () => AuthenticatedDashboardStartupRoute,
  } as any)
const AuthenticatedDashboardSmeServiceRoute =
  AuthenticatedDashboardSmeServiceRouteImport.update({
    id: '/$service',
    path: '/$service',
    getParentRoute: () => AuthenticatedDashboardSmeRoute,
  } as any)
const AuthenticatedDashboardCoursesSlugRoute =
  AuthenticatedDashboardCoursesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedDashboardCoursesRoute,
  } as any)
const AuthenticatedDashboardCdeModuleRoute =
  AuthenticatedDashboardCdeModuleRouteImport.update({
    id: '/$module',
    path: '/$module',
    getParentRoute: () => AuthenticatedDashboardCdeRoute,
  } as any)
const AuthenticatedDashboardAiChatThreadIdRoute =
  AuthenticatedDashboardAiChatThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedDashboardAiChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/dashboard/ai-chat': typeof AuthenticatedDashboardAiChatRouteWithChildren
  '/dashboard/analysis': typeof AuthenticatedDashboardAnalysisRoute
  '/dashboard/annual-tax': typeof AuthenticatedDashboardAnnualTaxRoute
  '/dashboard/appointments': typeof AuthenticatedDashboardAppointmentsRoute
  '/dashboard/audit': typeof AuthenticatedDashboardAuditRoute
  '/dashboard/cde': typeof AuthenticatedDashboardCdeRouteWithChildren
  '/dashboard/certificates': typeof AuthenticatedDashboardCertificatesRoute
  '/dashboard/clients': typeof AuthenticatedDashboardClientsRoute
  '/dashboard/company': typeof AuthenticatedDashboardCompanyRoute
  '/dashboard/compliance': typeof AuthenticatedDashboardComplianceRoute
  '/dashboard/courses': typeof AuthenticatedDashboardCoursesRouteWithChildren
  '/dashboard/discovery': typeof AuthenticatedDashboardDiscoveryRoute
  '/dashboard/enrollments': typeof AuthenticatedDashboardEnrollmentsRoute
  '/dashboard/evaluation': typeof AuthenticatedDashboardEvaluationRoute
  '/dashboard/g50': typeof AuthenticatedDashboardG50Route
  '/dashboard/health': typeof AuthenticatedDashboardHealthRoute
  '/dashboard/investment': typeof AuthenticatedDashboardInvestmentRoute
  '/dashboard/invoices': typeof AuthenticatedDashboardInvoicesRoute
  '/dashboard/kpi': typeof AuthenticatedDashboardKpiRoute
  '/dashboard/learning': typeof AuthenticatedDashboardLearningRoute
  '/dashboard/legal-library': typeof AuthenticatedDashboardLegalLibraryRoute
  '/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/dashboard/my-listings': typeof AuthenticatedDashboardMyListingsRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/dashboard/payroll': typeof AuthenticatedDashboardPayrollRoute
  '/dashboard/progress': typeof AuthenticatedDashboardProgressRoute
  '/dashboard/quizzes': typeof AuthenticatedDashboardQuizzesRoute
  '/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/dashboard/risk': typeof AuthenticatedDashboardRiskRoute
  '/dashboard/scf': typeof AuthenticatedDashboardScfRoute
  '/dashboard/schema': typeof AuthenticatedDashboardSchemaRoute
  '/dashboard/sme': typeof AuthenticatedDashboardSmeRouteWithChildren
  '/dashboard/startup': typeof AuthenticatedDashboardStartupRouteWithChildren
  '/dashboard/teaching': typeof AuthenticatedDashboardTeachingRoute
  '/dashboard/workspace': typeof AuthenticatedDashboardWorkspaceRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/ai-chat/$threadId': typeof AuthenticatedDashboardAiChatThreadIdRoute
  '/dashboard/cde/$module': typeof AuthenticatedDashboardCdeModuleRoute
  '/dashboard/courses/$slug': typeof AuthenticatedDashboardCoursesSlugRoute
  '/dashboard/sme/$service': typeof AuthenticatedDashboardSmeServiceRoute
  '/dashboard/startup/$service': typeof AuthenticatedDashboardStartupServiceRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/dashboard/ai-chat/': typeof AuthenticatedDashboardAiChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/chat': typeof ApiChatRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/dashboard/analysis': typeof AuthenticatedDashboardAnalysisRoute
  '/dashboard/annual-tax': typeof AuthenticatedDashboardAnnualTaxRoute
  '/dashboard/appointments': typeof AuthenticatedDashboardAppointmentsRoute
  '/dashboard/audit': typeof AuthenticatedDashboardAuditRoute
  '/dashboard/cde': typeof AuthenticatedDashboardCdeRouteWithChildren
  '/dashboard/certificates': typeof AuthenticatedDashboardCertificatesRoute
  '/dashboard/clients': typeof AuthenticatedDashboardClientsRoute
  '/dashboard/company': typeof AuthenticatedDashboardCompanyRoute
  '/dashboard/compliance': typeof AuthenticatedDashboardComplianceRoute
  '/dashboard/courses': typeof AuthenticatedDashboardCoursesRouteWithChildren
  '/dashboard/discovery': typeof AuthenticatedDashboardDiscoveryRoute
  '/dashboard/enrollments': typeof AuthenticatedDashboardEnrollmentsRoute
  '/dashboard/evaluation': typeof AuthenticatedDashboardEvaluationRoute
  '/dashboard/g50': typeof AuthenticatedDashboardG50Route
  '/dashboard/health': typeof AuthenticatedDashboardHealthRoute
  '/dashboard/investment': typeof AuthenticatedDashboardInvestmentRoute
  '/dashboard/invoices': typeof AuthenticatedDashboardInvoicesRoute
  '/dashboard/kpi': typeof AuthenticatedDashboardKpiRoute
  '/dashboard/learning': typeof AuthenticatedDashboardLearningRoute
  '/dashboard/legal-library': typeof AuthenticatedDashboardLegalLibraryRoute
  '/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/dashboard/my-listings': typeof AuthenticatedDashboardMyListingsRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/dashboard/payroll': typeof AuthenticatedDashboardPayrollRoute
  '/dashboard/progress': typeof AuthenticatedDashboardProgressRoute
  '/dashboard/quizzes': typeof AuthenticatedDashboardQuizzesRoute
  '/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/dashboard/risk': typeof AuthenticatedDashboardRiskRoute
  '/dashboard/scf': typeof AuthenticatedDashboardScfRoute
  '/dashboard/schema': typeof AuthenticatedDashboardSchemaRoute
  '/dashboard/sme': typeof AuthenticatedDashboardSmeRouteWithChildren
  '/dashboard/startup': typeof AuthenticatedDashboardStartupRouteWithChildren
  '/dashboard/teaching': typeof AuthenticatedDashboardTeachingRoute
  '/dashboard/workspace': typeof AuthenticatedDashboardWorkspaceRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/ai-chat/$threadId': typeof AuthenticatedDashboardAiChatThreadIdRoute
  '/dashboard/cde/$module': typeof AuthenticatedDashboardCdeModuleRoute
  '/dashboard/courses/$slug': typeof AuthenticatedDashboardCoursesSlugRoute
  '/dashboard/sme/$service': typeof AuthenticatedDashboardSmeServiceRoute
  '/dashboard/startup/$service': typeof AuthenticatedDashboardStartupServiceRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/dashboard/ai-chat': typeof AuthenticatedDashboardAiChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/_authenticated/dashboard/ai-chat': typeof AuthenticatedDashboardAiChatRouteWithChildren
  '/_authenticated/dashboard/analysis': typeof AuthenticatedDashboardAnalysisRoute
  '/_authenticated/dashboard/annual-tax': typeof AuthenticatedDashboardAnnualTaxRoute
  '/_authenticated/dashboard/appointments': typeof AuthenticatedDashboardAppointmentsRoute
  '/_authenticated/dashboard/audit': typeof AuthenticatedDashboardAuditRoute
  '/_authenticated/dashboard/cde': typeof AuthenticatedDashboardCdeRouteWithChildren
  '/_authenticated/dashboard/certificates': typeof AuthenticatedDashboardCertificatesRoute
  '/_authenticated/dashboard/clients': typeof AuthenticatedDashboardClientsRoute
  '/_authenticated/dashboard/company': typeof AuthenticatedDashboardCompanyRoute
  '/_authenticated/dashboard/compliance': typeof AuthenticatedDashboardComplianceRoute
  '/_authenticated/dashboard/courses': typeof AuthenticatedDashboardCoursesRouteWithChildren
  '/_authenticated/dashboard/discovery': typeof AuthenticatedDashboardDiscoveryRoute
  '/_authenticated/dashboard/enrollments': typeof AuthenticatedDashboardEnrollmentsRoute
  '/_authenticated/dashboard/evaluation': typeof AuthenticatedDashboardEvaluationRoute
  '/_authenticated/dashboard/g50': typeof AuthenticatedDashboardG50Route
  '/_authenticated/dashboard/health': typeof AuthenticatedDashboardHealthRoute
  '/_authenticated/dashboard/investment': typeof AuthenticatedDashboardInvestmentRoute
  '/_authenticated/dashboard/invoices': typeof AuthenticatedDashboardInvoicesRoute
  '/_authenticated/dashboard/kpi': typeof AuthenticatedDashboardKpiRoute
  '/_authenticated/dashboard/learning': typeof AuthenticatedDashboardLearningRoute
  '/_authenticated/dashboard/legal-library': typeof AuthenticatedDashboardLegalLibraryRoute
  '/_authenticated/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/_authenticated/dashboard/my-listings': typeof AuthenticatedDashboardMyListingsRoute
  '/_authenticated/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/_authenticated/dashboard/payroll': typeof AuthenticatedDashboardPayrollRoute
  '/_authenticated/dashboard/progress': typeof AuthenticatedDashboardProgressRoute
  '/_authenticated/dashboard/quizzes': typeof AuthenticatedDashboardQuizzesRoute
  '/_authenticated/dashboard/reports': typeof AuthenticatedDashboardReportsRoute
  '/_authenticated/dashboard/risk': typeof AuthenticatedDashboardRiskRoute
  '/_authenticated/dashboard/scf': typeof AuthenticatedDashboardScfRoute
  '/_authenticated/dashboard/schema': typeof AuthenticatedDashboardSchemaRoute
  '/_authenticated/dashboard/sme': typeof AuthenticatedDashboardSmeRouteWithChildren
  '/_authenticated/dashboard/startup': typeof AuthenticatedDashboardStartupRouteWithChildren
  '/_authenticated/dashboard/teaching': typeof AuthenticatedDashboardTeachingRoute
  '/_authenticated/dashboard/workspace': typeof AuthenticatedDashboardWorkspaceRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/ai-chat/$threadId': typeof AuthenticatedDashboardAiChatThreadIdRoute
  '/_authenticated/dashboard/cde/$module': typeof AuthenticatedDashboardCdeModuleRoute
  '/_authenticated/dashboard/courses/$slug': typeof AuthenticatedDashboardCoursesSlugRoute
  '/_authenticated/dashboard/sme/$service': typeof AuthenticatedDashboardSmeServiceRoute
  '/_authenticated/dashboard/startup/$service': typeof AuthenticatedDashboardStartupServiceRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/dashboard/ai-chat/': typeof AuthenticatedDashboardAiChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/features'
    | '/pricing'
    | '/reset-password'
    | '/dashboard'
    | '/api/chat'
    | '/verify/$code'
    | '/dashboard/ai-chat'
    | '/dashboard/analysis'
    | '/dashboard/annual-tax'
    | '/dashboard/appointments'
    | '/dashboard/audit'
    | '/dashboard/cde'
    | '/dashboard/certificates'
    | '/dashboard/clients'
    | '/dashboard/company'
    | '/dashboard/compliance'
    | '/dashboard/courses'
    | '/dashboard/discovery'
    | '/dashboard/enrollments'
    | '/dashboard/evaluation'
    | '/dashboard/g50'
    | '/dashboard/health'
    | '/dashboard/investment'
    | '/dashboard/invoices'
    | '/dashboard/kpi'
    | '/dashboard/learning'
    | '/dashboard/legal-library'
    | '/dashboard/messages'
    | '/dashboard/my-listings'
    | '/dashboard/notifications'
    | '/dashboard/payroll'
    | '/dashboard/progress'
    | '/dashboard/quizzes'
    | '/dashboard/reports'
    | '/dashboard/risk'
    | '/dashboard/scf'
    | '/dashboard/schema'
    | '/dashboard/sme'
    | '/dashboard/startup'
    | '/dashboard/teaching'
    | '/dashboard/workspace'
    | '/dashboard/'
    | '/dashboard/ai-chat/$threadId'
    | '/dashboard/cde/$module'
    | '/dashboard/courses/$slug'
    | '/dashboard/sme/$service'
    | '/dashboard/startup/$service'
    | '/lovable/email/queue/process'
    | '/dashboard/ai-chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/features'
    | '/pricing'
    | '/reset-password'
    | '/api/chat'
    | '/verify/$code'
    | '/dashboard/analysis'
    | '/dashboard/annual-tax'
    | '/dashboard/appointments'
    | '/dashboard/audit'
    | '/dashboard/cde'
    | '/dashboard/certificates'
    | '/dashboard/clients'
    | '/dashboard/company'
    | '/dashboard/compliance'
    | '/dashboard/courses'
    | '/dashboard/discovery'
    | '/dashboard/enrollments'
    | '/dashboard/evaluation'
    | '/dashboard/g50'
    | '/dashboard/health'
    | '/dashboard/investment'
    | '/dashboard/invoices'
    | '/dashboard/kpi'
    | '/dashboard/learning'
    | '/dashboard/legal-library'
    | '/dashboard/messages'
    | '/dashboard/my-listings'
    | '/dashboard/notifications'
    | '/dashboard/payroll'
    | '/dashboard/progress'
    | '/dashboard/quizzes'
    | '/dashboard/reports'
    | '/dashboard/risk'
    | '/dashboard/scf'
    | '/dashboard/schema'
    | '/dashboard/sme'
    | '/dashboard/startup'
    | '/dashboard/teaching'
    | '/dashboard/workspace'
    | '/dashboard'
    | '/dashboard/ai-chat/$threadId'
    | '/dashboard/cde/$module'
    | '/dashboard/courses/$slug'
    | '/dashboard/sme/$service'
    | '/dashboard/startup/$service'
    | '/lovable/email/queue/process'
    | '/dashboard/ai-chat'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/features'
    | '/pricing'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/api/chat'
    | '/verify/$code'
    | '/_authenticated/dashboard/ai-chat'
    | '/_authenticated/dashboard/analysis'
    | '/_authenticated/dashboard/annual-tax'
    | '/_authenticated/dashboard/appointments'
    | '/_authenticated/dashboard/audit'
    | '/_authenticated/dashboard/cde'
    | '/_authenticated/dashboard/certificates'
    | '/_authenticated/dashboard/clients'
    | '/_authenticated/dashboard/company'
    | '/_authenticated/dashboard/compliance'
    | '/_authenticated/dashboard/courses'
    | '/_authenticated/dashboard/discovery'
    | '/_authenticated/dashboard/enrollments'
    | '/_authenticated/dashboard/evaluation'
    | '/_authenticated/dashboard/g50'
    | '/_authenticated/dashboard/health'
    | '/_authenticated/dashboard/investment'
    | '/_authenticated/dashboard/invoices'
    | '/_authenticated/dashboard/kpi'
    | '/_authenticated/dashboard/learning'
    | '/_authenticated/dashboard/legal-library'
    | '/_authenticated/dashboard/messages'
    | '/_authenticated/dashboard/my-listings'
    | '/_authenticated/dashboard/notifications'
    | '/_authenticated/dashboard/payroll'
    | '/_authenticated/dashboard/progress'
    | '/_authenticated/dashboard/quizzes'
    | '/_authenticated/dashboard/reports'
    | '/_authenticated/dashboard/risk'
    | '/_authenticated/dashboard/scf'
    | '/_authenticated/dashboard/schema'
    | '/_authenticated/dashboard/sme'
    | '/_authenticated/dashboard/startup'
    | '/_authenticated/dashboard/teaching'
    | '/_authenticated/dashboard/workspace'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/ai-chat/$threadId'
    | '/_authenticated/dashboard/cde/$module'
    | '/_authenticated/dashboard/courses/$slug'
    | '/_authenticated/dashboard/sme/$service'
    | '/_authenticated/dashboard/startup/$service'
    | '/lovable/email/queue/process'
    | '/_authenticated/dashboard/ai-chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiChatRoute: typeof ApiChatRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/workspace': {
      id: '/_authenticated/dashboard/workspace'
      path: '/workspace'
      fullPath: '/dashboard/workspace'
      preLoaderRoute: typeof AuthenticatedDashboardWorkspaceRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/teaching': {
      id: '/_authenticated/dashboard/teaching'
      path: '/teaching'
      fullPath: '/dashboard/teaching'
      preLoaderRoute: typeof AuthenticatedDashboardTeachingRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/startup': {
      id: '/_authenticated/dashboard/startup'
      path: '/startup'
      fullPath: '/dashboard/startup'
      preLoaderRoute: typeof AuthenticatedDashboardStartupRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/sme': {
      id: '/_authenticated/dashboard/sme'
      path: '/sme'
      fullPath: '/dashboard/sme'
      preLoaderRoute: typeof AuthenticatedDashboardSmeRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/schema': {
      id: '/_authenticated/dashboard/schema'
      path: '/schema'
      fullPath: '/dashboard/schema'
      preLoaderRoute: typeof AuthenticatedDashboardSchemaRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/scf': {
      id: '/_authenticated/dashboard/scf'
      path: '/scf'
      fullPath: '/dashboard/scf'
      preLoaderRoute: typeof AuthenticatedDashboardScfRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/risk': {
      id: '/_authenticated/dashboard/risk'
      path: '/risk'
      fullPath: '/dashboard/risk'
      preLoaderRoute: typeof AuthenticatedDashboardRiskRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/reports': {
      id: '/_authenticated/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof AuthenticatedDashboardReportsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/quizzes': {
      id: '/_authenticated/dashboard/quizzes'
      path: '/quizzes'
      fullPath: '/dashboard/quizzes'
      preLoaderRoute: typeof AuthenticatedDashboardQuizzesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/progress': {
      id: '/_authenticated/dashboard/progress'
      path: '/progress'
      fullPath: '/dashboard/progress'
      preLoaderRoute: typeof AuthenticatedDashboardProgressRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/payroll': {
      id: '/_authenticated/dashboard/payroll'
      path: '/payroll'
      fullPath: '/dashboard/payroll'
      preLoaderRoute: typeof AuthenticatedDashboardPayrollRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/notifications': {
      id: '/_authenticated/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof AuthenticatedDashboardNotificationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/my-listings': {
      id: '/_authenticated/dashboard/my-listings'
      path: '/my-listings'
      fullPath: '/dashboard/my-listings'
      preLoaderRoute: typeof AuthenticatedDashboardMyListingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/messages': {
      id: '/_authenticated/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof AuthenticatedDashboardMessagesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/legal-library': {
      id: '/_authenticated/dashboard/legal-library'
      path: '/legal-library'
      fullPath: '/dashboard/legal-library'
      preLoaderRoute: typeof AuthenticatedDashboardLegalLibraryRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/learning': {
      id: '/_authenticated/dashboard/learning'
      path: '/learning'
      fullPath: '/dashboard/learning'
      preLoaderRoute: typeof AuthenticatedDashboardLearningRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/kpi': {
      id: '/_authenticated/dashboard/kpi'
      path: '/kpi'
      fullPath: '/dashboard/kpi'
      preLoaderRoute: typeof AuthenticatedDashboardKpiRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/invoices': {
      id: '/_authenticated/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof AuthenticatedDashboardInvoicesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/investment': {
      id: '/_authenticated/dashboard/investment'
      path: '/investment'
      fullPath: '/dashboard/investment'
      preLoaderRoute: typeof AuthenticatedDashboardInvestmentRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/health': {
      id: '/_authenticated/dashboard/health'
      path: '/health'
      fullPath: '/dashboard/health'
      preLoaderRoute: typeof AuthenticatedDashboardHealthRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/g50': {
      id: '/_authenticated/dashboard/g50'
      path: '/g50'
      fullPath: '/dashboard/g50'
      preLoaderRoute: typeof AuthenticatedDashboardG50RouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/evaluation': {
      id: '/_authenticated/dashboard/evaluation'
      path: '/evaluation'
      fullPath: '/dashboard/evaluation'
      preLoaderRoute: typeof AuthenticatedDashboardEvaluationRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/enrollments': {
      id: '/_authenticated/dashboard/enrollments'
      path: '/enrollments'
      fullPath: '/dashboard/enrollments'
      preLoaderRoute: typeof AuthenticatedDashboardEnrollmentsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/discovery': {
      id: '/_authenticated/dashboard/discovery'
      path: '/discovery'
      fullPath: '/dashboard/discovery'
      preLoaderRoute: typeof AuthenticatedDashboardDiscoveryRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/courses': {
      id: '/_authenticated/dashboard/courses'
      path: '/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof AuthenticatedDashboardCoursesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/compliance': {
      id: '/_authenticated/dashboard/compliance'
      path: '/compliance'
      fullPath: '/dashboard/compliance'
      preLoaderRoute: typeof AuthenticatedDashboardComplianceRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/company': {
      id: '/_authenticated/dashboard/company'
      path: '/company'
      fullPath: '/dashboard/company'
      preLoaderRoute: typeof AuthenticatedDashboardCompanyRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/clients': {
      id: '/_authenticated/dashboard/clients'
      path: '/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof AuthenticatedDashboardClientsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/certificates': {
      id: '/_authenticated/dashboard/certificates'
      path: '/certificates'
      fullPath: '/dashboard/certificates'
      preLoaderRoute: typeof AuthenticatedDashboardCertificatesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/cde': {
      id: '/_authenticated/dashboard/cde'
      path: '/cde'
      fullPath: '/dashboard/cde'
      preLoaderRoute: typeof AuthenticatedDashboardCdeRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/audit': {
      id: '/_authenticated/dashboard/audit'
      path: '/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof AuthenticatedDashboardAuditRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/appointments': {
      id: '/_authenticated/dashboard/appointments'
      path: '/appointments'
      fullPath: '/dashboard/appointments'
      preLoaderRoute: typeof AuthenticatedDashboardAppointmentsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/annual-tax': {
      id: '/_authenticated/dashboard/annual-tax'
      path: '/annual-tax'
      fullPath: '/dashboard/annual-tax'
      preLoaderRoute: typeof AuthenticatedDashboardAnnualTaxRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/analysis': {
      id: '/_authenticated/dashboard/analysis'
      path: '/analysis'
      fullPath: '/dashboard/analysis'
      preLoaderRoute: typeof AuthenticatedDashboardAnalysisRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/ai-chat': {
      id: '/_authenticated/dashboard/ai-chat'
      path: '/ai-chat'
      fullPath: '/dashboard/ai-chat'
      preLoaderRoute: typeof AuthenticatedDashboardAiChatRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/ai-chat/': {
      id: '/_authenticated/dashboard/ai-chat/'
      path: '/'
      fullPath: '/dashboard/ai-chat/'
      preLoaderRoute: typeof AuthenticatedDashboardAiChatIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardAiChatRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/startup/$service': {
      id: '/_authenticated/dashboard/startup/$service'
      path: '/$service'
      fullPath: '/dashboard/startup/$service'
      preLoaderRoute: typeof AuthenticatedDashboardStartupServiceRouteImport
      parentRoute: typeof AuthenticatedDashboardStartupRoute
    }
    '/_authenticated/dashboard/sme/$service': {
      id: '/_authenticated/dashboard/sme/$service'
      path: '/$service'
      fullPath: '/dashboard/sme/$service'
      preLoaderRoute: typeof AuthenticatedDashboardSmeServiceRouteImport
      parentRoute: typeof AuthenticatedDashboardSmeRoute
    }
    '/_authenticated/dashboard/courses/$slug': {
      id: '/_authenticated/dashboard/courses/$slug'
      path: '/$slug'
      fullPath: '/dashboard/courses/$slug'
      preLoaderRoute: typeof AuthenticatedDashboardCoursesSlugRouteImport
      parentRoute: typeof AuthenticatedDashboardCoursesRoute
    }
    '/_authenticated/dashboard/cde/$module': {
      id: '/_authenticated/dashboard/cde/$module'
      path: '/$module'
      fullPath: '/dashboard/cde/$module'
      preLoaderRoute: typeof AuthenticatedDashboardCdeModuleRouteImport
      parentRoute: typeof AuthenticatedDashboardCdeRoute
    }
    '/_authenticated/dashboard/ai-chat/$threadId': {
      id: '/_authenticated/dashboard/ai-chat/$threadId'
      path: '/$threadId'
      fullPath: '/dashboard/ai-chat/$threadId'
      preLoaderRoute: typeof AuthenticatedDashboardAiChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedDashboardAiChatRoute
    }
  }
}

interface AuthenticatedDashboardAiChatRouteChildren {
  AuthenticatedDashboardAiChatThreadIdRoute: typeof AuthenticatedDashboardAiChatThreadIdRoute
  AuthenticatedDashboardAiChatIndexRoute: typeof AuthenticatedDashboardAiChatIndexRoute
}

const AuthenticatedDashboardAiChatRouteChildren: AuthenticatedDashboardAiChatRouteChildren =
  {
    AuthenticatedDashboardAiChatThreadIdRoute:
      AuthenticatedDashboardAiChatThreadIdRoute,
    AuthenticatedDashboardAiChatIndexRoute:
      AuthenticatedDashboardAiChatIndexRoute,
  }

const AuthenticatedDashboardAiChatRouteWithChildren =
  AuthenticatedDashboardAiChatRoute._addFileChildren(
    AuthenticatedDashboardAiChatRouteChildren,
  )

interface AuthenticatedDashboardCdeRouteChildren {
  AuthenticatedDashboardCdeModuleRoute: typeof AuthenticatedDashboardCdeModuleRoute
}

const AuthenticatedDashboardCdeRouteChildren: AuthenticatedDashboardCdeRouteChildren =
  {
    AuthenticatedDashboardCdeModuleRoute: AuthenticatedDashboardCdeModuleRoute,
  }

const AuthenticatedDashboardCdeRouteWithChildren =
  AuthenticatedDashboardCdeRoute._addFileChildren(
    AuthenticatedDashboardCdeRouteChildren,
  )

interface AuthenticatedDashboardCoursesRouteChildren {
  AuthenticatedDashboardCoursesSlugRoute: typeof AuthenticatedDashboardCoursesSlugRoute
}

const AuthenticatedDashboardCoursesRouteChildren: AuthenticatedDashboardCoursesRouteChildren =
  {
    AuthenticatedDashboardCoursesSlugRoute:
      AuthenticatedDashboardCoursesSlugRoute,
  }

const AuthenticatedDashboardCoursesRouteWithChildren =
  AuthenticatedDashboardCoursesRoute._addFileChildren(
    AuthenticatedDashboardCoursesRouteChildren,
  )

interface AuthenticatedDashboardSmeRouteChildren {
  AuthenticatedDashboardSmeServiceRoute: typeof AuthenticatedDashboardSmeServiceRoute
}

const AuthenticatedDashboardSmeRouteChildren: AuthenticatedDashboardSmeRouteChildren =
  {
    AuthenticatedDashboardSmeServiceRoute:
      AuthenticatedDashboardSmeServiceRoute,
  }

const AuthenticatedDashboardSmeRouteWithChildren =
  AuthenticatedDashboardSmeRoute._addFileChildren(
    AuthenticatedDashboardSmeRouteChildren,
  )

interface AuthenticatedDashboardStartupRouteChildren {
  AuthenticatedDashboardStartupServiceRoute: typeof AuthenticatedDashboardStartupServiceRoute
}

const AuthenticatedDashboardStartupRouteChildren: AuthenticatedDashboardStartupRouteChildren =
  {
    AuthenticatedDashboardStartupServiceRoute:
      AuthenticatedDashboardStartupServiceRoute,
  }

const AuthenticatedDashboardStartupRouteWithChildren =
  AuthenticatedDashboardStartupRoute._addFileChildren(
    AuthenticatedDashboardStartupRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAiChatRoute: typeof AuthenticatedDashboardAiChatRouteWithChildren
  AuthenticatedDashboardAnalysisRoute: typeof AuthenticatedDashboardAnalysisRoute
  AuthenticatedDashboardAnnualTaxRoute: typeof AuthenticatedDashboardAnnualTaxRoute
  AuthenticatedDashboardAppointmentsRoute: typeof AuthenticatedDashboardAppointmentsRoute
  AuthenticatedDashboardAuditRoute: typeof AuthenticatedDashboardAuditRoute
  AuthenticatedDashboardCdeRoute: typeof AuthenticatedDashboardCdeRouteWithChildren
  AuthenticatedDashboardCertificatesRoute: typeof AuthenticatedDashboardCertificatesRoute
  AuthenticatedDashboardClientsRoute: typeof AuthenticatedDashboardClientsRoute
  AuthenticatedDashboardCompanyRoute: typeof AuthenticatedDashboardCompanyRoute
  AuthenticatedDashboardComplianceRoute: typeof AuthenticatedDashboardComplianceRoute
  AuthenticatedDashboardCoursesRoute: typeof AuthenticatedDashboardCoursesRouteWithChildren
  AuthenticatedDashboardDiscoveryRoute: typeof AuthenticatedDashboardDiscoveryRoute
  AuthenticatedDashboardEnrollmentsRoute: typeof AuthenticatedDashboardEnrollmentsRoute
  AuthenticatedDashboardEvaluationRoute: typeof AuthenticatedDashboardEvaluationRoute
  AuthenticatedDashboardG50Route: typeof AuthenticatedDashboardG50Route
  AuthenticatedDashboardHealthRoute: typeof AuthenticatedDashboardHealthRoute
  AuthenticatedDashboardInvestmentRoute: typeof AuthenticatedDashboardInvestmentRoute
  AuthenticatedDashboardInvoicesRoute: typeof AuthenticatedDashboardInvoicesRoute
  AuthenticatedDashboardKpiRoute: typeof AuthenticatedDashboardKpiRoute
  AuthenticatedDashboardLearningRoute: typeof AuthenticatedDashboardLearningRoute
  AuthenticatedDashboardLegalLibraryRoute: typeof AuthenticatedDashboardLegalLibraryRoute
  AuthenticatedDashboardMessagesRoute: typeof AuthenticatedDashboardMessagesRoute
  AuthenticatedDashboardMyListingsRoute: typeof AuthenticatedDashboardMyListingsRoute
  AuthenticatedDashboardNotificationsRoute: typeof AuthenticatedDashboardNotificationsRoute
  AuthenticatedDashboardPayrollRoute: typeof AuthenticatedDashboardPayrollRoute
  AuthenticatedDashboardProgressRoute: typeof AuthenticatedDashboardProgressRoute
  AuthenticatedDashboardQuizzesRoute: typeof AuthenticatedDashboardQuizzesRoute
  AuthenticatedDashboardReportsRoute: typeof AuthenticatedDashboardReportsRoute
  AuthenticatedDashboardRiskRoute: typeof AuthenticatedDashboardRiskRoute
  AuthenticatedDashboardScfRoute: typeof AuthenticatedDashboardScfRoute
  AuthenticatedDashboardSchemaRoute: typeof AuthenticatedDashboardSchemaRoute
  AuthenticatedDashboardSmeRoute: typeof AuthenticatedDashboardSmeRouteWithChildren
  AuthenticatedDashboardStartupRoute: typeof AuthenticatedDashboardStartupRouteWithChildren
  AuthenticatedDashboardTeachingRoute: typeof AuthenticatedDashboardTeachingRoute
  AuthenticatedDashboardWorkspaceRoute: typeof AuthenticatedDashboardWorkspaceRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAiChatRoute:
      AuthenticatedDashboardAiChatRouteWithChildren,
    AuthenticatedDashboardAnalysisRoute: AuthenticatedDashboardAnalysisRoute,
    AuthenticatedDashboardAnnualTaxRoute: AuthenticatedDashboardAnnualTaxRoute,
    AuthenticatedDashboardAppointmentsRoute:
      AuthenticatedDashboardAppointmentsRoute,
    AuthenticatedDashboardAuditRoute: AuthenticatedDashboardAuditRoute,
    AuthenticatedDashboardCdeRoute: AuthenticatedDashboardCdeRouteWithChildren,
    AuthenticatedDashboardCertificatesRoute:
      AuthenticatedDashboardCertificatesRoute,
    AuthenticatedDashboardClientsRoute: AuthenticatedDashboardClientsRoute,
    AuthenticatedDashboardCompanyRoute: AuthenticatedDashboardCompanyRoute,
    AuthenticatedDashboardComplianceRoute:
      AuthenticatedDashboardComplianceRoute,
    AuthenticatedDashboardCoursesRoute:
      AuthenticatedDashboardCoursesRouteWithChildren,
    AuthenticatedDashboardDiscoveryRoute: AuthenticatedDashboardDiscoveryRoute,
    AuthenticatedDashboardEnrollmentsRoute:
      AuthenticatedDashboardEnrollmentsRoute,
    AuthenticatedDashboardEvaluationRoute:
      AuthenticatedDashboardEvaluationRoute,
    AuthenticatedDashboardG50Route: AuthenticatedDashboardG50Route,
    AuthenticatedDashboardHealthRoute: AuthenticatedDashboardHealthRoute,
    AuthenticatedDashboardInvestmentRoute:
      AuthenticatedDashboardInvestmentRoute,
    AuthenticatedDashboardInvoicesRoute: AuthenticatedDashboardInvoicesRoute,
    AuthenticatedDashboardKpiRoute: AuthenticatedDashboardKpiRoute,
    AuthenticatedDashboardLearningRoute: AuthenticatedDashboardLearningRoute,
    AuthenticatedDashboardLegalLibraryRoute:
      AuthenticatedDashboardLegalLibraryRoute,
    AuthenticatedDashboardMessagesRoute: AuthenticatedDashboardMessagesRoute,
    AuthenticatedDashboardMyListingsRoute:
      AuthenticatedDashboardMyListingsRoute,
    AuthenticatedDashboardNotificationsRoute:
      AuthenticatedDashboardNotificationsRoute,
    AuthenticatedDashboardPayrollRoute: AuthenticatedDashboardPayrollRoute,
    AuthenticatedDashboardProgressRoute: AuthenticatedDashboardProgressRoute,
    AuthenticatedDashboardQuizzesRoute: AuthenticatedDashboardQuizzesRoute,
    AuthenticatedDashboardReportsRoute: AuthenticatedDashboardReportsRoute,
    AuthenticatedDashboardRiskRoute: AuthenticatedDashboardRiskRoute,
    AuthenticatedDashboardScfRoute: AuthenticatedDashboardScfRoute,
    AuthenticatedDashboardSchemaRoute: AuthenticatedDashboardSchemaRoute,
    AuthenticatedDashboardSmeRoute: AuthenticatedDashboardSmeRouteWithChildren,
    AuthenticatedDashboardStartupRoute:
      AuthenticatedDashboardStartupRouteWithChildren,
    AuthenticatedDashboardTeachingRoute: AuthenticatedDashboardTeachingRoute,
    AuthenticatedDashboardWorkspaceRoute: AuthenticatedDashboardWorkspaceRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiChatRoute: ApiChatRoute,
  VerifyCodeRoute: VerifyCodeRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
